source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

pod 'AFNetworking', '~> 3.0'
pod 'BlocksKit', '~> 2.2.5'
pod 'TPKeyboardAvoiding'
pod 'MJRefresh'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'Masonry'

pod 'INTULocationManager', '~> 4.2.0'
pod 'SDWebImage', '~> 3.8.0'